Repository NiksBrn/Giga-Algebra, pull requests merged in 2024-11, with the labels that each got.

#4 part of the first module
  sources/tmp_modules/first_module_NN.cpp
  tests/NaturalNumberTest.cpp
Labels: bug, draft

#9 the second module
  sources/tmp_modules/tmp_integer.cpp
Labels: bug, draft

#8 GUI
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/.qmake.stash
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/Makefile
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/Makefile.Debug
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/Makefile.Release
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/IntegerNumber.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/NaturalNumber.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/NaturalNumbers.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/Overload.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/Polynomial.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/RationalNumber.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/Struct.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/giga.exe
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/main.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/mainwindow.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/moc_mainwindow.cpp
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/moc_mainwindow.o
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/moc_predefs.h
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/debug/object_script.giga.Debug
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/release/object_script.giga.Release
  GUI/build-giga-Desktop_Qt_6_6_2_MinGW_64_bit-Debug/ui_mainwindow.h
  GUI/sources/equal.xml
  GUI/sources/giga.pro
  GUI/sources/giga.pro.user
  GUI/sources/main.cpp
  GUI/sources/mainwindow.cpp
  GUI/sources/mainwindow.h
  GUI/sources/mainwindow.ui
  GUI/sources/mainwindow.ui.autosave
Labels: draft, GUI

#12 hot fix
  sources/tmp_modules/first_module_NN.cpp
  tests/NaturalNumberTest.cpp
Labels: hot, cold

#14 LAST FIX??
  sources/tmp_modules/first_module_NN.cpp
  tests/NaturalNumberTest.cpp
Labels: bug, draft

#10 second part of the first module
  sources/tmp_modules/first_module_NN2.cpp
Labels: bug, draft, no tests

#17 ALL_MODULES_IN
  headers/IntegerNumber.h
  sources/tmp_modules/all_modules_IN.cpp
  tests/IntegerNumberTest.cpp
Labels: bug, duplicate, draft

#18 NN Optimization
  headers/NaturalNumber.h
  main.cpp
  sources/tmp_modules/first_module_NN.cpp
  sources/tmp_modules/first_module_NN2.cpp
  tests/NaturalNumberTest.cpp
  tests/NaturalNumberTest2.cpp
Labels: hot

#19 RationalNumber_TEST
  tests/RationalNumberTest.cpp
Labels: cold

#20 fix:done
  sources/tmp_modules/P_modules_DIV_PP_P.cpp
  sources/tmp_modules/all_modules_IN.cpp
  sources/tmp_modules/first_module_NN2.cpp
  tests/IntegerNumberTest.cpp
Labels: bug, draft, hot

#24 Ivan_global_fix
  headers/Polynomial.h
  headers/Struct.h
  headers/StructPolynomial.h
  sources/modules/Polynomial.cpp
  sources/overload/Overload.cpp
  sources/struct/Struct.cpp
  sources/struct/StructPolynomial.cpp
  sources/tmp_modules/P_modules_DIV_PP_P.cpp
  sources/tmp_modules/all_mdules_P.cpp
  tests/PolynomialTest.cpp
Labels: hot

#26 DIV_PP_P:fix
  sources/tmp_modules/P_modules_DIV_PP_P.cpp
  tests/DIV_PP_P_test.cpp
Labels: ok

#27 DIV_PP_P:fix2
  sources/tmp_modules/P_modules_DIV_PP_P.cpp
Labels: ok

#28 sub_nn_n fix
  sources/modules/NaturalNumber.cpp
  tests/NaturalNumberTest.cpp
Labels: ok
